packages:
  - .
ignoredBuiltDependencies:
  - gifsicle
  - jpegtran-bin
  - mozjpeg
  - pngquant-bin
onlyBuiltDependencies:
  - cwebp-bin
  - esbuild
  - optipng-bin
overrides:
  got@<11.8.5: '>=11.8.5'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  object-path@<0.11.6: '>=0.11.6'
  trim-newlines@<3.0.1: '>=3.0.1'
  object-path@<0.11.5: '>=0.11.5'
  object-path@<0.11.8: '>=0.11.8'
  cross-spawn@<6.0.6: '>=6.0.6'
  esbuild@<=0.24.2: '>=0.25.0'
  http-cache-semantics@<4.1.1: '>=4.1.1'
