import React from 'react';
import { Card, Text, Button, Group, Stack, Badge, TextInput } from '@mantine/core';
import { useStyles } from '../hooks/useStyles';

/**
 * Example component that demonstrates how to use the StyleService with Mantine
 */
export function ThemeExample() {
  const { 
    isDark, 
    theme,
    cardStyles, 
    textStyles, 
    buttonStyles,
    inputStyles 
  } = useStyles();

  return (
    <Card {...cardStyles} mt="md">
      <Stack gap="md">
        <Text {...textStyles} size="xl" fw={700}>Theme Integration Example</Text>
        
        <Text {...textStyles}>
          This component demonstrates how our StyleService integrates with Mantine's theme system.
          All styles are generated by the StyleService and consistently applied throughout the app.
        </Text>
        
        <Group>
          <Badge color={isDark ? 'blue.4' : 'blue.6'}>Mantine Theme</Badge>
          <Badge color={isDark ? 'green.4' : 'green.6'}>StyleService</Badge>
        </Group>
        
        <TextInput
          label={<Text {...textStyles}>Sample Input</Text>}
          placeholder="Type something..."
          styles={{
            input: inputStyles,
            label: inputStyles
          }}
        />
        
        <Group>
          <Button {...buttonStyles} color="blue">Primary Button</Button>
          <Button {...buttonStyles} color="gray">Secondary Button</Button>
          <Button {...buttonStyles} variant="outline">Outline Button</Button>
        </Group>
        
        <Text size="sm" c={isDark ? 'gray.4' : 'gray.6'} ta="center">
          Current theme mode: {isDark ? 'Dark' : 'Light'}
        </Text>
      </Stack>
    </Card>
  );
}
