name: Cache Invalidation

on:
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup GitHub Actions cache
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Invalidating cache...');
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            for (const cache of caches.data.actions_caches) {
              console.log(`Deleting cache with id ${cache.id}, key: ${cache.key}`);
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id
              });
            }
            
            console.log('Cache invalidation complete');
